// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace POPpiciOS
{
	public partial class DVCGameListMyTurn : DVCGames
	{
		public DVCGameListMyTurn (IntPtr handle) : base (handle)
		{
			this.ListType = POPpicLibrary.MyGamesViewModel.ListType.MY_TURN;
		}
	}
}
