// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace POPpiciOS
{
	public partial class GameplayControlsOverlayView : UIView
	{
		public GameplayControlsOverlayView (IntPtr handle) : base (handle)
		{
			var newFrame = this.Frame;
		}

		public override UIView HitTest (System.Drawing.PointF point, UIEvent uievent)
		{
			var result = base.HitTest (point, uievent);
			if (result as UIButton != null) {
				return result; // If you pressed a button then we should pass that along
			}
			return null;
		}
	}
}
