// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace POPpiciOS
{
	public partial class SplashScreenViewController : UIViewController
	{
		public SplashScreenViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
