// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using POPpicLibrary;
using System.Collections.Generic;
using System.Drawing;

namespace POPpiciOS
{
	public partial class TrophiesFullSizeViewController : UIViewController
	{
		public TrophiesFullSizeViewController (IntPtr handle) : base (handle)
		{
		}

		UIView giantView;
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.TabBarController.TabBar.Hidden = true;
			this.scrollView.PagingEnabled = true;
			giantView = new UIView ();
			giantView.BackgroundColor = UIColor.Cyan;
			this.scrollView.AddSubview (giantView);

			this.pageControl.Pages = this.viewModel.MyBuddyPictures.Count;
			this.pageControl.CurrentPage = this.currentIndex;
			this.scrollView.Scrolled += (object sender, EventArgs e) => {
				LoadVisiblePages ();
			};

			var pageScrollViewSize = this.scrollView.Frame.Size;
			this.scrollView.ContentSize = new System.Drawing.SizeF (pageScrollViewSize.Width * this.pageControl.Pages, pageScrollViewSize.Height);

			var myFrame = this.scrollView.Frame;
			var visibleFrame = new RectangleF (myFrame.Width * this.currentIndex, myFrame.Y, myFrame.Width, myFrame.Height);
			this.scrollView.ScrollRectToVisible (visibleFrame, false);
			LoadVisiblePages ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			var myFrame = this.scrollView.Frame;
			var visibleFrame = new RectangleF (myFrame.Width * this.currentIndex, myFrame.Y, myFrame.Width, myFrame.Height);
			this.scrollView.ScrollRectToVisible (visibleFrame, false);
		}

		public override void ViewDidLayoutSubviews ()
		{
			base.ViewDidLayoutSubviews ();

			var myFrame = this.scrollView.Frame;
			var visibleFrame = new RectangleF (myFrame.Width * this.currentIndex, myFrame.Y, myFrame.Width, myFrame.Height);
			this.scrollView.ScrollRectToVisible (visibleFrame, false);
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			var myFrame = this.scrollView.Frame;
			var visibleFrame = new RectangleF (myFrame.Width * this.currentIndex, myFrame.Y, myFrame.Width, myFrame.Height);
			this.scrollView.ScrollRectToVisible (visibleFrame, false);
		}

		private void LoadPage(int index)
		{
			if (index < 0 || index >= this.pageControl.Pages) {
				// If it's outside the range of what you have to display, then do nothing
				return;
			}

			UIImageView pageView;
			if (this.pages.ContainsKey (index)) {
				pageView = this.pages [index];
			} else {
				var myFrame = this.scrollView.Frame;
				RectangleF frame = new RectangleF (myFrame.Width * index, myFrame.Y, myFrame.Width, myFrame.Height);
				pageView = new UIImageView (frame);
				pageView.ContentMode = UIViewContentMode.ScaleAspectFit;

				var imageItem = this.viewModel.MyBuddyPictures [index];
				IOSUtilities.SetImageFromStream (PopPicImageCache.GetPhotoAlbumImage (0, imageItem.PhotoID, imageItem.FullUrl),
					pageView,
					this);

				// this.scrollView.AddSubview (pageView);
				this.giantView.AddSubview (pageView);
			}

			this.pages [index] = pageView;
		}

		private void PurgePage(int index)
		{
			if (index < 0 || index >= this.pageControl.Pages) {
				// If it's outside the range of what you have to display, then do nothing
				return;
			}

			if (this.pages.ContainsKey (index)) {
				var pageView = this.pages [index];
				pageView.RemoveFromSuperview ();
				this.pages.Remove (index);
			}
		}

		private void LoadVisiblePages()
		{
			var pageWidth = this.scrollView.Frame.Width;
			int page = (int)Math.Floor (((this.scrollView.ContentOffset.X * 2.0f) + pageWidth) / (pageWidth * 2.0f));
			this.pageControl.CurrentPage = page;

			int firstPage = page - 1;
			int lastPage = page + 1;

			for (int i = firstPage - 1; i >= 0; i--) {
				PurgePage (i);
			}

			for (int i = lastPage + 1; i < this.pageControl.Pages; i++) {
				PurgePage (i);
			}

			for (int i = firstPage; i <= lastPage; i++) {
				LoadPage (i);
			}

		}

		MyTrophiesViewModel viewModel = null;
		int currentIndex = -1;
		Dictionary<int, UIImageView> pages = new Dictionary<int, UIImageView> ();
		public void SetViewModel(MyTrophiesViewModel viewModel, int currentIndex) {
			this.viewModel = viewModel;
			this.currentIndex = currentIndex;
		}
	}
}
