#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("POPpic.Resource", IsApplication=true)]

namespace POPpic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::POPpic.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::POPpic.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::POPpic.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::POPpic.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::POPpic.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::POPpic.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::POPpic.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::POPpic.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::POPpic.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::POPpic.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::POPpic.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::POPpic.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::POPpic.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::POPpic.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::POPpic.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::POPpic.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::POPpic.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::POPpic.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::POPpic.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::POPpic.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::POPpic.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::POPpic.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::POPpic.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::POPpic.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::POPpic.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::POPpic.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::POPpic.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::POPpic.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::POPpic.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::POPpic.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::POPpic.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::POPpic.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::POPpic.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::POPpic.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::POPpic.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::POPpic.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::POPpic.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Gcm.Client.Resource.String.library_name = global::POPpic.Resource.String.library_name;
			global::FacebookMonoDroid.Resource.String.library_name = global::POPpic.Resource.String.library_name;
			global::POPpicLibrary.Resource.String.library_name = global::POPpic.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010015
			public const int ahBarColor = 2130771989;
			
			// aapt resource value: 0x7f01001d
			public const int ahBarLength = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int ahBarWidth = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int ahCircleColor = 2130771994;
			
			// aapt resource value: 0x7f010019
			public const int ahDelayMillis = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int ahRadius = 2130771995;
			
			// aapt resource value: 0x7f010016
			public const int ahRimColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int ahRimWidth = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int ahSpinSpeed = 2130771992;
			
			// aapt resource value: 0x7f010012
			public const int ahText = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int ahTextColor = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int ahTextSize = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public const int confirm_logout = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int done_button_background = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int done_button_text = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int extra_fields = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int fetch_user_info = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int is_cropped = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int login_text = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int logout_text = 2130771983;
			
			// aapt resource value: 0x7f010007
			public const int multi_select = 2130771975;
			
			// aapt resource value: 0x7f010010
			public const int preset_size = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int radius_in_meters = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int results_limit = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int search_text = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int show_pictures = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int show_search_box = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int show_title_bar = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int title_bar_background = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int title_text = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07000e
			public const int aqua = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int black = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int blue = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int blue_background = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_blue = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_text_color = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int fuchsia = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int gray = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int green = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int lime = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int maroon = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int navy = 2131165203;
			
			// aapt resource value: 0x7f07000b
			public const int olive = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int purple = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int red = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int silver = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int teal = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int white = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int yellow = 2131165190;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080007
			public const int com_facebook_loginview_height = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int com_facebook_loginview_padding_bottom = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int com_facebook_loginview_padding_left = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int com_facebook_loginview_padding_right = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int com_facebook_loginview_padding_top = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int com_facebook_loginview_text_size = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int com_facebook_loginview_width = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int com_facebook_profilepictureview_preset_size_large = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int com_facebook_profilepictureview_preset_size_small = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int balloon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int balloon_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int balloon_gray = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int balloon_green = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int balloon_orange = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int balloonbackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int balloonbackground_small = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_check = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_check_off = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_check_on = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_grey_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_grey_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_grey_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_close = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_list_divider = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_list_section_header_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_loginbutton_blue = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_loginbutton_blue_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_loginbutton_blue_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_loginbutton_blue_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_loginbutton_silver = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_logo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_picker_item_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_picker_list_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_picker_list_longpressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_picker_list_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_picker_list_selector = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_picker_list_selector_background_transition = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_picker_list_selector_disabled = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_picker_top_button = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_place_default_icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_profile_default_icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_profile_picture_blank_portrait = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_profile_picture_blank_square = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_top_background = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_top_button = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int facebook_icon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int GameListItemBackground = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_expand = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_new = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_next_item = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_action_refresh = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_view_as_grid = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_errorstatus = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_successstatus = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Icon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ImageryGalleryBackground = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int LoserPictureBorder = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int MyGamesListViewBackground = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int outerspace = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int popImage = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int roundedbg = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int roundedbgdark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int splashscreen = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int UserInfoBorder = 2130837560;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int balloonContainerRelativeLayout = 2131034115;
			
			// aapt resource value: 0x7f050029
			public const int balloonOverlay = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int bodyLayout = 2131034152;
			
			// aapt resource value: 0x7f050005
			public const int button1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_login_activity_progress_bar = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_picker_activity_circle = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_picker_checkbox = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int com_facebook_picker_checkbox_stub = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int com_facebook_picker_divider = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int com_facebook_picker_done_button = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int com_facebook_picker_image = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int com_facebook_picker_list_section_header = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_picker_list_view = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int com_facebook_picker_profile_pic_stub = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_picker_row_activity_circle = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int com_facebook_picker_title = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int com_facebook_picker_title_bar = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int com_facebook_picker_title_bar_stub = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int com_facebook_picker_top_bar = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int com_facebook_placepickerfragment_search_box_stub = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int com_facebook_usersettingsfragment_login_button = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int com_facebook_usersettingsfragment_logo_image = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int com_facebook_usersettingsfragment_profile_name = 2131034141;
			
			// aapt resource value: 0x7f050047
			public const int create_game = 2131034183;
			
			// aapt resource value: 0x7f05001f
			public const int fragmentcontainer = 2131034143;
			
			// aapt resource value: 0x7f050027
			public const int frameLayout = 2131034151;
			
			// aapt resource value: 0x7f050036
			public const int friendListItem = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int gallery1 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int gallery2 = 2131034168;
			
			// aapt resource value: 0x7f050006
			public const int gameOverOverlay = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int gameoverTextView = 2131034121;
			
			// aapt resource value: 0x7f05003e
			public const int greeting = 2131034174;
			
			// aapt resource value: 0x7f050043
			public const int gridView1 = 2131034179;
			
			// aapt resource value: 0x7f050007
			public const int imageView1 = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int imageView2 = 2131034149;
			
			// aapt resource value: 0x7f050002
			public const int large = 2131034114;
			
			// aapt resource value: 0x7f05002c
			public const int leftPlayerImage = 2131034156;
			
			// aapt resource value: 0x7f05002f
			public const int leftPlayerNameText = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int leftplayerTimeText = 2131034158;
			
			// aapt resource value: 0x7f050020
			public const int linearLayout1 = 2131034144;
			
			// aapt resource value: 0x7f05002a
			public const int linearLayout2 = 2131034154;
			
			// aapt resource value: 0x7f05002d
			public const int linearLayout3 = 2131034157;
			
			// aapt resource value: 0x7f050032
			public const int linearLayout4 = 2131034162;
			
			// aapt resource value: 0x7f050042
			public const int listView1 = 2131034178;
			
			// aapt resource value: 0x7f05003b
			public const int loadingImage = 2131034171;
			
			// aapt resource value: 0x7f050039
			public const int loadingProgressBar = 2131034169;
			
			// aapt resource value: 0x7f05003c
			public const int loadingProgressWheel = 2131034172;
			
			// aapt resource value: 0x7f050041
			public const int loadingRelativeLayout = 2131034177;
			
			// aapt resource value: 0x7f05003f
			public const int login_button = 2131034175;
			
			// aapt resource value: 0x7f05003d
			public const int main_ui_container = 2131034173;
			
			// aapt resource value: 0x7f050024
			public const int myGameListItemLayout = 2131034148;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int picker_subtitle = 2131034139;
			
			// aapt resource value: 0x7f050023
			public const int progressBar1 = 2131034147;
			
			// aapt resource value: 0x7f050046
			public const int refresh_games = 2131034182;
			
			// aapt resource value: 0x7f050022
			public const int relativeLayout1 = 2131034146;
			
			// aapt resource value: 0x7f05002b
			public const int relativeLayout2 = 2131034155;
			
			// aapt resource value: 0x7f050030
			public const int relativeLayout3 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int rightPlayerImage = 2131034161;
			
			// aapt resource value: 0x7f050034
			public const int rightPlayerNameText = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int rightplayerTimeText = 2131034163;
			
			// aapt resource value: 0x7f050044
			public const int rootLayout = 2131034180;
			
			// aapt resource value: 0x7f050040
			public const int rootLinearLayout = 2131034176;
			
			// aapt resource value: 0x7f050035
			public const int scrollView1 = 2131034165;
			
			// aapt resource value: 0x7f05001a
			public const int search_box = 2131034138;
			
			// aapt resource value: 0x7f050000
			public const int small = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050021
			public const int textView2 = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int textView3 = 2131034150;
			
			// aapt resource value: 0x7f05003a
			public const int textViewStatus = 2131034170;
			
			// aapt resource value: 0x7f050008
			public const int textureView1 = 2131034120;
			
			// aapt resource value: 0x7f050045
			public const int view_trophies = 2131034181;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BalloonOverlayLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_friendpickerfragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_login_activity_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_picker_activity_circle_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_picker_checkbox = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_image = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_list_row = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_list_section_header = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_search_box = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_title_bar = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_picker_title_bar_stub = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_placepickerfragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_placepickerfragment_list_row = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_usersettingsfragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int CreateGameLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int FriendListItemLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int GameImageryLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int GameListItemLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int GameOverOverLayLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int GameplayLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int GameSetupFragmentLayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int GamesListDividerItem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int loading = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int loadingimage = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int loadingprogress = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int loginPage = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int MyGamesLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int MyGamesListView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int MyTrophiesFragmentLayout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int MyTrophiesFullSizeImageLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int MyTrophiesGalleryThumbnailLayout = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int MyTrophiesLayout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int SelectFriendLayout = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int SelectFriendSourceLayout = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int SplashScreenLayout = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int UserInfoBoxLayout = 2130903075;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int MyGamesMenu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int aria02 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BalloonPop = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060028
			public const int app_id = 2131099688;
			
			// aapt resource value: 0x7f06001a
			public const int app_name = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int cancelled = 2131099675;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_choose_friends = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_dialogloginactivity_ok_button = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_internet_permission_error_message = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_internet_permission_error_title = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_loading = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_loginview_cancel_action = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_loginview_log_in_button = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_loginview_log_out_action = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_loginview_log_out_button = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_loginview_logged_in_as = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_loginview_logged_in_using_facebook = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_logo_content_description = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_nearby = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_picker_done_button_text = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_placepicker_subtitle_format = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_requesterror_password_changed = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_requesterror_permissions = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_requesterror_reconnect = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_requesterror_relogin = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_requesterror_web_login = 2131099668;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_usersettingsfragment_log_in_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_usersettingsfragment_logged_in = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131099658;
			
			// aapt resource value: 0x7f06002b
			public const int create_game = 2131099691;
			
			// aapt resource value: 0x7f060021
			public const int error = 2131099681;
			
			// aapt resource value: 0x7f060029
			public const int exception = 2131099689;
			
			// aapt resource value: 0x7f06001e
			public const int hello_user = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int library_name = 2131099673;
			
			// aapt resource value: 0x7f06002c
			public const int my_trophies = 2131099692;
			
			// aapt resource value: 0x7f060025
			public const int no_friends_selected = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int no_place_selected = 2131099686;
			
			// aapt resource value: 0x7f06001d
			public const int ok = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int permission_not_granted = 2131099676;
			
			// aapt resource value: 0x7f060023
			public const int photo_post = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int pick_seattle_place = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int refresh_games = 2131099690;
			
			// aapt resource value: 0x7f060022
			public const int status_update = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int success = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int successfully_posted_post = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int you_picked = 2131099684;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090003
			public const int CreateGameHeaders = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int Theme_Splash = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int com_facebook_loginview_default_style = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int com_facebook_loginview_silver_style = 2131296257;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] com_facebook_friend_picker_fragment = new int[]
			{
					2130771975};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_login_view = new int[]
			{
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[]
			{
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[]
			{
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
